version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000" 
    volumes:
      - .:/usr/src/app 
    depends_on:
      - db
    environment:
      MYSQL_HOST: db 
      MYSQL_PORT: 3306
      MYSQL_USER: root 
      MYSQL_PASS: my-secret-pw 
      MYSQL_DB: cyclecommunity 

  db:
    image: mysql:latest
    ports:
      - "3307:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw 
      MYSQL_DATABASE: cyclecommunity 

    volumes:
      - db-data:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80" 
    environment:
      PMA_HOST: db 
      PMA_PORT: 3306 
    depends_on:
      - db

volumes:
  db-data: 
